### signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Ciclano",
    "email": "ciclano@gmail.com",
	"password": "123456",
    "role": "NORMAL"
}

### login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "fulano@gmail.com",
	"password": "123456"
}

### register
POST http://localhost:3003/band/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyN2IwNmVhLTkxMGUtNGExMS04OTMxLTljMmIzOGQyMTIxNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMzA4MTQxMywiZXhwIjoxNjEzMDgxNzEzfQ.1rweVyO6gMJkeNqX9vo03wsyQo9JJyPZlWJQbFW_CcQ
Content-Type: application/json

{
    "name": "Ciclanos",
    "music_genre": "Rock",
  	"responsible": "Ciclano da Silva"
}


### Get band by id
GET http://localhost:3003/band/details/:id
Content-Type: application/json

{
	"responsible": "Ciclano"
}

